### ISSUE TITLE
RuntimeException: cannot load JavaScript engine

### ISSUE THREAD

**Issue by antokara** [siddii/scriptmonkey#6]
I get the following exception when starting up Intellij:

RuntimeException: com.boxysystems.scriptmonkey.intellij.ScriptMonkeyPlugin@4852d3d1: cannot load JavaScript engine

Details:
com.boxysystems.scriptmonkey.intellij.ScriptMonkeyPlugin@fb349d: cannot load JavaScript engine
java.lang.RuntimeException: cannot load JavaScript engine
	at com.boxysystems.scriptmonkey.intellij.ui.ScriptCommandProcessor.createScriptEngine(ScriptCommandProcessor.java:170)
	at com.boxysystems.scriptmonkey.intellij.ui.ScriptCommandProcessor.<init>(ScriptCommandProcessor.java:66)
	at com.boxysystems.scriptmonkey.intellij.ScriptMonkeyPlugin.projectOpened(ScriptMonkeyPlugin.java:41)
	at com.intellij.openapi.project.impl.ProjectImpl.projectOpened(ProjectImpl.java:412)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:74)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:447)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$2.projectOpened(ProjectManagerImpl.java:156)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.fireProjectOpened(ProjectManagerImpl.java:1068)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:422)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.loadAndOpenProject(ProjectManagerImpl.java:513)
	at com.intellij.ide.impl.ProjectUtil.openProject(ProjectUtil.java:181)
	at com.intellij.ide.RecentProjectsManager.doOpenProject(RecentProjectsManager.java:45)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:345)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:370)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:209)
	at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
	at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
	at com.sun.proxy.$Proxy34.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication.loadProject(IdeaApplication.java:284)
	at com.intellij.idea.IdeaApplication.access$500(IdeaApplication.java:56)
	at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:261)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:319)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:697)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by drinchev** [comment]
+1 

I have the following error when I try to start WebStorm :

Plugin 'Script Monkey' failed to initialize and will be disabled.  Please restart WebStorm.

com.intellij.diagnostic.PluginException: com/boxysystems/scriptmonkey/intellij/ScriptMonkeyApplicationComponent : Unsupported major.minor version 52.0 [Plugin: Script Monkey]
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:130)
    at com.intellij.ide.plugins.cl.PluginClassLoader.a(PluginClassLoader.java:77)
    at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:66)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:249)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:427)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.a(ComponentManagerImpl.java:417)
    at com.intellij.openapi.components.impl.ComponentManagerImpl$ComponentsRegistry.access$000(ComponentManagerImpl.java:403)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.a(ComponentManagerImpl.java:108)
    at com.intellij.openapi.components.impl.ComponentManagerImpl.init(ComponentManagerImpl.java:87)
    at com.intellij.openapi.components.impl.stores.ApplicationStoreImpl.load(ApplicationStoreImpl.java:101)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:499)
    at com.intellij.openapi.application.impl.ApplicationImpl.load(ApplicationImpl.java:481)
    at com.intellij.idea.IdeaApplication.run(IdeaApplication.java:170)
    at com.intellij.idea.MainImpl$1$1$1.run(MainImpl.java:64)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
    at java.awt.EventQueue.access$400(EventQueue.java:82)
    at java.awt.EventQueue$2.run(EventQueue.java:676)
    at java.awt.EventQueue$2.run(EventQueue.java:674)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:362)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
Caused by: java.lang.UnsupportedClassVersionError: com/boxysystems/scriptmonkey/intellij/ScriptMonkeyApplicationComponent : Unsupported major.minor version 52.0
    at java.lang.ClassLoader.defineClass1(Native Method)
    at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
    at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:259)
    at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:255)
    at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:231)
    at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:124)
    ... 30 more

**Comment by vsch** [comment]
I have made changes to the class loader and it now works on IDEA 14 Community and IDEA 15 EAP Community. I think it will fix this issue but if @antokara and @drinchev are willing to try the new version and let me know for sure that it fixes their issue, I will merge the PR.

You can download it from the forked project, pullable branch <https://github.com/vsch/scriptmonkey/tree/pullable/dist> and clicking on ScriptMonkey_1.1.1.zip or by clicking on this link: <https://github.com/vsch/scriptmonkey/blob/pullable/dist/ScriptMonkey_1.1.1.zip?raw=true>.

@drinchev, @antokara, Please let me know if it works for you.

Thanks.

**Comment by vsch** [comment]
New version that works on IDEA 14 and IDEA 15 EAP in the new develop branch. I will help @siddii spiff it up for new versions and add functionality. I think having the ability to extend the IDEA with JS is awesome.

Spiffed up shell script pane now uses standard editor and JS syntax highlighting, follows UI theme and has all the advanced editor features. Also, fixed `plugin-script/timebar.js`, now working under this version. Can download dev version at [ScriptMonkey_1.2.1.zip](https://github.com/siddii/scriptmonkey/blob/develop/ScriptMonkey_1.2.1.zip?raw=true)

**Comment by siddii** [comment]
@vsch - I just updated the plugin on Jetbrain repository - https://plugins.jetbrains.com/plugin/3674
Let me know if its looks fine.

**Comment by drinchev** [comment]
Hey there all.

Sorry for the delay.

Unfortunately there is some strange behaviour with the plugin under OS X with WebStorm.

WebStorm 10, while this time not crashing, shows that there is a problem with the plugin :

```
com.boxysystems.scriptmonkey.intellij.ScriptMonkeyPlugin@4e04b048: Cannot load scripting engine!
java.lang.RuntimeException: Cannot load scripting engine!
	at com.boxysystems.scriptmonkey.intellij.ui.ScriptCommandProcessor.getScriptingEngine(ScriptCommandProcessor.java:229)
	at com.boxysystems.scriptmonkey.intellij.ui.ScriptCommandProcessor.createScriptEngine(ScriptCommandProcessor.java:204)
	at com.boxysystems.scriptmonkey.intellij.ui.ScriptCommandProcessor.<init>(ScriptCommandProcessor.java:68)
	at com.boxysystems.scriptmonkey.intellij.ScriptMonkeyPlugin.projectOpened(ScriptMonkeyPlugin.java:37)
	at com.intellij.openapi.project.impl.ProjectImpl.c(ProjectImpl.java:385)
	at com.intellij.openapi.project.impl.ProjectImpl.access$200(ProjectImpl.java:73)
	at com.intellij.openapi.project.impl.ProjectImpl$MyProjectManagerListener.projectOpened(ProjectImpl.java:420)
	at com.intellij.openapi.project.impl.ProjectManagerImpl$3.projectOpened(ProjectManagerImpl.java:154)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.e(ProjectManagerImpl.java:938)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.openProject(ProjectManagerImpl.java:461)
	at com.intellij.platform.PlatformProjectOpenProcessor.doOpenProject(PlatformProjectOpenProcessor.java:222)
	at com.intellij.ide.RecentDirectoryProjectsManager.doOpenProject(RecentDirectoryProjectsManager.java:56)
	at com.intellij.ide.RecentProjectsManagerBase.doReopenLastProject(RecentProjectsManagerBase.java:357)
	at com.intellij.ide.RecentProjectsManagerBase$MyAppLifecycleListener.appStarting(RecentProjectsManagerBase.java:384)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:116)
	at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:322)
	at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:309)
	at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:288)
	at com.intellij.util.messages.impl.MessageBusImpl.access$200(MessageBusImpl.java:41)
	at com.intellij.util.messages.impl.MessageBusImpl$2.invoke(MessageBusImpl.java:177)
	at com.sun.proxy.$Proxy43.appStarting(Unknown Source)
	at com.intellij.idea.IdeaApplication$IdeStarter$2.run(IdeaApplication.java:328)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:332)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:734)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:569)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:382)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

and refuses to load.

While this is for WebStorm 10, I tried it with WebStorm 11 EAP ( Beta ). In 11 there is no error at all and I can actually compile and execute JS scripts via ScriptMonkey (huray!), but it seems that there is nothing in the global namespace, except `window` which is some sort of Rhino reference for the container of the script window.

My best bet is that under OS X, WebStorm 10 is using some OS X Java ( made by Apple ), which I guess doesn't have Rhino inside. This makes sense, because on WebStorm 11 EAP, JetBrains declared that they have implemented their own custom JDK, specially for OS X.

However, I'm really stuck to figure out, why under WebStorm 11 EAP there are no globals. Even `alert`, `console` are unidentified.

I'm attaching a GIF video, how WS 11 EAP works with ScriptMonkey under OS X

![11-eap](https://cloud.githubusercontent.com/assets/202919/9683359/b565b3ce-530f-11e5-811d-a91bdb3df902.gif)

**Comment by vsch** [comment]
@drinchev, thanks for the partially good news. I will be adding more instructions and trouble shooting to `develop` branch readme.  This section of the readme: <https://github.com/siddii/scriptmonkey/tree/develop#version-12x-wip-switch-to-nashorn-engine> has a bit more information on the changes to nashorn script engine from rhino.

- nashorn is not rhino but your issue goes beyond that. However, if you want to know there are some differences between Rhino and Nashorn, see the [Rhino Migration Guide](https://wiki.openjdk.java.net/display/Nashorn/Rhino+Migration+Guide).

- Webstorm EAP probably runs under the bundled jdk 1.8 if you downloaded the version with the bundled jdk. For WebStrom 10 **you will need to run your IDEA under jdk 1.8** to do this you need to refer to the instructions [Selecting the JDK version the IDE will run under](https://intellij-support.jetbrains.com/hc/en-us/articles/206827547-Selecting-the-JDK-version-the-IDE-will-run-under). For MacOS it involves editing the Info.plist in the application contents and changing the `JVMVersion` from `1.6*,1.7+` to `1.6+,1.8+` final result should look something like:

    ```
          <key>JVMVersion</key>
          <string>1.6+,1.8+</string>
    ```

    To get to the Info.plist file:
    
    1. go to Applications, select your Intellij app:

        ![screen shot 2015-09-04 at 1 29 51 pm](https://cloud.githubusercontent.com/assets/10299086/9690341/c691195a-5309-11e5-8a5d-b42ed3c0dfb6.png)

    2. on the context menu select show package contents:

        ![screen shot 2015-09-04 at 1 30 30 pm](https://cloud.githubusercontent.com/assets/10299086/9690340/c690f466-5309-11e5-9e5b-6c1e0266456c.png)

- the globals are acting funny. The only globals defined are: `engine` `application` `project` `plugin` `windowManager` `window` and in my IntelliJ Community and PhpStorm they are available. However, the `window` is added separately into global scope, for some reason it works fine. 

    1. I changed the initialization for all globals to be the same as that for `window` but since both versions worked for me can't test whether it fixes your issue. 
    2. Can you please try out the new build and let me know if it fixes the missing globals for you., **it can be downloaded from here: https://github.com/siddii/scriptmonkey/blob/develop/ScriptMonkey_1.2.x.zip?raw=true**

**Comment by vsch** [comment]
@drinchev, I downloaded WebStorm 10, 30 day trial and the released version of the plugin works in it, even without the latest modifications. However, it is the one with the bundled jdk.

Can you let me know under what jdk your WebStorm 11 EAP is running? nashorn is actively updated so every jdk release has a different flavour.

![screen shot 2015-09-04 at 3 02 35 pm](https://cloud.githubusercontent.com/assets/10299086/9692325/556cee2c-5316-11e5-89e2-8992dba466c0.png)

**Comment by drinchev** [comment]
@vsch,

Thanks for the fast reply.

WS 11 is running JetBrains' bundled Java VM
WS 10 is running Apple's JRE

![screen shot 2015-09-04 at 22 18 27]
(https://cloud.githubusercontent.com/assets/202919/9693757/285c17a4-5353-11e5-823b-ed4504006e1e.png)
![screen shot 2015-09-04 at 22 19 06](https://cloud.githubusercontent.com/assets/202919/9693758/2864a752-5353-11e5-9564-16bf4e732ffc.png)

Unfortunately the zip file doesn't resolve the issue with the globals on WS 11

I don't want to change VMs for 10, because under OS X there are a lot of problems with the [font rendering](https://youtrack.jetbrains.com/issue/IDEA-132281).

I'm using OS X 10.10.5

So I guess the problem with the globals is the one that is unsolved now. The OS JDK on WS 10 is a blocker as far as I can see and anyway after JetBrains fixed the issue with the font antialiasing I think most of the users will not bother using the embeded JDK for 13+.

**Comment by vsch** [comment]
I haven't noticed any issues. I am running on an iMac Retina and have been using both the IntelliJ SDK's and the Oracle downloaded ones. Rendering is fine and jre 1.6 is very stale. My own plugin will stop supporting jdk 1.6 after the very next release. I can't afford the time to chase 'fleas' in the buggy implementation that is fixed in the newer jdk. Same for this plugin. Having to support many backward versions of the jdk makes maintenance a serious chore that leaves no room for new development.

**Comment by drinchev** [comment]
:+1: I would do the same if I were you :) . I guess let's wait for WebStorm 11 release and check what JetBrains has embed as JDK.

**Comment by vsch** [comment]
For my plugin I had to find the JavaFX library dynamically and load classes through reflection API otherwise it could hang the IDE if it was using the bundled JDK on the Mac. Once I am done making that configurable, I'll transfer the same code to this plugin. My hope is that the needed libraries can be loaded from a jdk that is not the one the IDEA runs on. Then this plugin can work with any JDK as long as the needed jars from 1.8 are installed somewhere on the system.

I don't see why this would not work but then.... I will let you know as soon as I find a solution.

**Comment by vsch** [comment]
@drinchev, I Just checked the latest dev build 1.2.7 and it works on Mac OS X with the bundled JDK 1.8 so it may solve not finding the nashorn library under Windows also since I re-implemented the class loader as per my plugin.

If it is not too much trouble can you please try it out and let me know if it works for you. Download it from the develop branch <https://github.com/siddii/scriptmonkey/blob/develop/ScriptMonkey_1.2.x.zip?raw=true>

**Comment by drinchev** [comment]
@vsch :( Unfortunately I still don't have the globals ... 

I'm using the freshly WS 11 EAP with Jetbrain's OpenJDK

![screen shot 2015-09-12 at 18 57 11](https://cloud.githubusercontent.com/assets/202919/9832614/cb36240a-5980-11e5-83fa-5c5e3ccd13e6.png)

**Comment by vsch** [comment]
I have the same WebStorm 11 EAP, bundled JDK, cleared all preferences and created an empty react boiler plate. Script Monkey works and has globals.

@drinchev, it just occurred to me that you probably had a much older version installed. Script Monkey expands its js.jar into your home directory ~/ScriptMonkey. I haven't familiarized myself with that bit of code but it looks like it should be updating that directory and renaming any existing files .bak before copying new ones.

These script files create all the JS globals as opposed to the Java bound JS globals. Globals like alert() are defined in ~/scriptMonkey/js/global/gui.js

Can you rename your ~/scriptMonkey to something like ~/scriptMonkey.bak and restart WebStorm, the plugin should recreate the directory with fresh files. 

I double checked and the js.jar contents in the build zip I linked for you has the same files as in my dev directory and my ~/scriptMonkey directory. So this would be the only other variable that I can think of that would affect the globals in Script Monkey.

**Comment by vsch** [comment]
@drinchev, I just duplicated your error. I renamed the ~/scriptMonkey to ~/scriptMonkey.bak and it is not recreated. The globals are missing. I'll have it fixed and send you a link to a new zip with the fixes. I was behind the :8ball: on this one.

**Comment by drinchev** [comment]
I checked, I don't have ~/scriptMonkey directory. It's strange `mdfind ScriptMonkey` only finds the `.jar` file inside `~/Library/Application Support/WebStorm11`. Do you know how can I debug why I don't have `~/scriptMonkey` directory created?

**Comment by vsch** [comment]
I am on it right now. Could have been something I inadvertently broke when I was doing some directory movements. I am still unfamiliar with parts of code that I didn't need to fix.

**Comment by vsch** [comment]
Found it. Yes, I caused it by starting to move artifact building to idea from Ant build but did not complete it. The jar was there but in the wrong place so it wasn't expanded into the classes directory for the plugin where it was looking for it. I'll have a new build in a few minutes and let you know.

**Comment by vsch** [comment]
Not entirely my fault. I fixed what I caused but I discovered the same issue in my own plugin too. During debug the plugin jar file is expanded and you have access to its contents as directories and files in the file system. Runtime environment does not do that (I suspect it used to in previous versons) and you have to get the resources as getResourceAsStream() because the file does not exist in the file system. During debugging the plugin created the directory and copied the files. Testing by installing into my runtime environment failed to create the directory.

It will take a bit longer but no need to wait. Here is the link to the js.jar file: <https://github.com/siddii/scriptmonkey/blob/develop/src/main/resources/com/boxysystems/scriptmonkey/intellij/js.jar?raw=true> extract it to your `~/scriptMonkey` directory and launch WebStorm. I am willing to bet it will work. You should have this as the resul (less tmp):

<img width="310" alt="screen shot 2015-09-12 at 3 21 50 pm" src="https://cloud.githubusercontent.com/assets/10299086/9833366/17a62020-5962-11e5-9b6a-5eec19adfbb9.png">


I will have to look into processing the jar as a reasource stream in the mean time.

**Comment by drinchev** [comment]
This is what I did and had no effect :

1. Unpacked the jar file to `~/scriptMonkey` . My directory looks like this now :

```
/Users/drinchev/scriptMonkey
├── global
│   ├── gui.js
│   ├── init.js
│   └── intellij.js
├── lib
│   └── trimpath.js
├── plugin-script
│   ├── codespointer.js
│   ├── timebar.js
│   └── tools.js
└── samples
    ├── AntVersion.js
    ├── BackupProjectFolder.js
    ├── EchoEnvironmentVariables.js
    ├── FileStatistics.js
    ├── HelloRhino.js
    └── ZipAndEmailProject.js

4 directories, 13 files
```

2. Restarted WebStorm 11. ( Had no effect )
3. Reinstall the plugin from the last zip file ( 1.2.x ) ( Had no effect )

I guess scriptMonkey doesn't read that directory at all. Maybe an exception if the path has not been read will be good to debug more.

**Comment by vsch** [comment]
Sorry, my bad, did not check the code carefully enough. Expand the js.jar to  `~/scriptMonkey/js` or just create the js directory under `~/scriptMonkey` and move the global, lib, plugin-script and samples directories from `~/scriptMonkey` to `~/scriptMonkey/js`. Whichever is easier for you.

**Comment by drinchev** [comment]
Wow :) :+1: 

![screen shot 2015-09-12 at 21 41 40](https://cloud.githubusercontent.com/assets/202919/9833427/1977d1a2-5997-11e5-8d75-e5a08587c349.png)

**Comment by vsch** [comment]
Glad to hear it. It was driving me nuts until I realized I was stuck in the code and not the environment.

I can confirm running an IntelliJ product prior to the EAP's does create the directory. So it is a change in the new versions of the products that causes the problem. You should be able to run WebStorm 10 with the dev build of the plugin. It would have created the directory.

I'll have it fixed for everyone else to enjoy too.

**Comment by vsch** [comment]
@siddii, I merged version 1.2.8 into master. Can you please update the plugin on JetBrains plugins page. The version that is there now is half baked with too many bugs. This one should be a better option.

In the meantime, anyone wanting an updated version can download it from the dist directory of this project's master branch: <https://github.com/siddii/scriptmonkey/blob/master/dist/ScriptMonkey_1.2.8.zip?raw=true>

**Comment by siddii** [comment]
@vsch - I just uploaded the plugin. Awesome work!

Thanks a million for your effort :+1:

**Comment by vsch** [comment]
My pleasure. I was going to write a plugin from scratch just so I can have JS for macro scripting. You saved me a ton of time, all I can do is return the favour. I think you did a great job.

Best regards,


Vladimir.
